# Generated by Django 2.1.1 on 2018-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('motivo', models.CharField(default='', max_length=20)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
